openapi: 3.0.0
info:
  title: API_DOCUMENTATION_TEMPLATE
  description: Some documentation for your API
  version: 1.0.0
  license: { name: private, url: none }
servers:
  - url: "http://dev-server.com"
    description: my dev host.
  - url: "http://stg-server.com"
    description: my stg host.
tags:
  - name: Schemas
    description: Group DB schemas together
components:
  schemas:
    User:
      $ref: models\User.yaml
paths:
  